version: '3'

services: 
    backend:
        container_name: python-server
        restart: always
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports: 
            - "8000:8000"