version: "3"

networks:
  isolation-network:
    driver: bridge

services:
  backend:
    container_name: python-server
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    networks:
      - isolation-network
  server:
    container_name: express-server
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    networks:
      - isolation-network

  client:
    container_name: react-nginx
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - isolation-network
