version: '3'

services: 
    backend:
        container_name: python-server
        restart: always
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports: 
            - "8000:8000"

    server:
        container_name: express-server
        restart: always
        build: 
            context: ./backend
            dockerfile: ./Dockerfile
            args:
                - NODE_ENV=production
        ports:
            - "3001:3001"
    
    client:
        container_name: react-nginx
        restart: always
        build:
            context: ./client
            dockerfile: ./Dockerfile
            args:
                - NODE_ENV=production
        ports: 
            - "8080:80"
        depends_on: 
            - server
            - backend